[gspread]
type = "service_account"
project_id = "projekt1-376511"
private_key_id = "6072b68fd93668984be3f52baeb78e27eefeae12"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCuDg2iylvXDQM1
WxqdzfHPZGTW3M5oT+vdrx1uYqIpAq15kFquaSrcNuOdMoWkCLaAqs1nO86iWc8b
+ZIBzGr4hdpD9MAFPsiG4xRmGkXIMjIoDFPgFZV0JX0Ud4oAaiauFjPo+6OdyAOo
FO52iFUIj3HGqq8rLEvx8q8cqAVJ6baYOrd/fhMyMZD7KEcGLvpf2U5zn9cQ+FEo
Z+woRWFoM7E0K9Vjp3OnE1D53yfv6eh7+pFEK3WsXP+JqpnyndJDbZ3rJ+GIIrpI
2eXDvnGDG3EkIETszNMmyVRJIkXXsyxh2YnCRlKKMVLEso0RzsqioRQdyQXtVua1
tWS5cobPAgMBAAECggEAEGAZGf5A4BLaK5cWgiSXQfms37wmx+XxB8p1vJDCDJVd
vdNTfMI/Oo2yzMjX4u7A64pmSHag17cXBweWxt2Kbjb6/ywT3sp2h55DU+HX5osL
xfx27bJffRhufqefz68s/sbu+6tPzESToijUpfPopXqywSFbg/Z8b1ceRitr/UqR
gHj9VAP+xCYIOR1b9r7GuhweFzBgKcAFAWGc6tB55bEJId+10s+R9O+jhNFf9hd2
6qJMlnnZAaCGRA8ShYfdYkrYiEge0krScK9QOaLoye5usmZ2giU2BZ5QA4cE1tfo
hahYlMN9a0DlBdHrcs3cHJYgSkD8Ws++gIVbRA9u8QKBgQDx/x9kd6iWEWe5iJSD
GCFF03I4NrIlI5UZfEd0QNvfkI3xBYmwjm9xhIt4gTd7YhY5bNIDNELadzKLKhIO
Fm7b28+XsBDxD1+xW52VJlrKFBZZLMI6M0EOmY0XhSfWygJFJne1BfpG/3ERETf3
/596V8Py72FtiVcUAgSwtHmAEQKBgQC4IHWdroicgO8xgN0Ad6UVzEI1pfkpEzX4
xmdNK4IHf9LOZ/3dglLG7aiz8zsTezcvHvDJGQumLwGB4KTfyWaYQrJ+XjciFXL2
Zude2dz7oleZwxMFSAJ931poy9oIniAzarShh+57J/M80hLrLegjt4tHoEQuj1PL
2qXh6lR43wKBgQDIaVOTPbHFjmaLdbwgkWRE0qc+PLXuIfjB4XW/plMxZCLZH4/3
Qw6yQWXMB59uND5ZknCerLJNAPg/3jiTqCppNDJI2kw9h1DlrgzkT55Syq3zbijw
UDApqir59pGWxTd6EzCCH5A1Kil2S/9BCFcH2BV0ZKEYOOx/qmg9+0jAMQKBgQCi
dnGQ+gksHk/vXAakfO06+ImLELFyXrMGmPlZDASlXVHCMdu78VvcjqKGdR0xKU0d
1K0co2616U/pKzAPDYPq4R7hhXwcJNTVOSL5fD4SAcJNt+Q2ir04FzWMtiHh7LP4
6jQLOwdfv3ZNugZbYJwtt6u7PVwrwOdtPbWUStDR/QKBgQCXgSZ7+TDIv39sSBNf
1Cns2KNDJCa5ZT03lY/AD9vHUtKb0jZ7ugxOfH9C/Yx5tIqKSVXMVVEIPpkCWePB
Jdmtg4QIwMSu6x1TBJTqgvVk+VmArLux1DEI3UAk6X+YL18wF9jhRiTCfsvmDf8X
NUcFeTKwAQP/BC/Z/h+G+OwYXQ==
-----END PRIVATE KEY-----
"""
  email = "blood-donations@projekt1-376511.iam.gserviceaccount.com"
  client_id = "118289070245337398252"
  auth_uri = "https://accounts.google.com/o/oauth2/auth"
  token_uri = "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/blood-donations%40projekt1-376511.iam.gserviceaccount.com"
  universe_domain = "googleapis.com"
  sheet = "Blood_donations"
